security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        master_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                provider: master_provider
            json_login:
                check_path:    app_api_login
                username_path: username
                password_path: password
            logout:
                path: /logout
                target: /

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                path:     /
                always_remember_me: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/Users/maker , roles: IS_AUTHENTICATED_ANONYMOUSLY,  methods: POST }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api , roles: ROLE_ADMIN,  methods: DELETE }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api , roles: ROLE_USER}
        - { path: ^/, roles: ROLE_USER }
