version: '3'
services:
    apache:
        build: .docker/apache
        container_name: clothecare_sf4_apache
        environment:
          VIRTUAL_HOST: clothecare.trifall.net, clothecare,clothecare.urenapi.nl, localhost
          VIRTUAL_PORT: 80
        expose:
          - 80
        ports:
          - 8086:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php
        restart: always

    clothecare_mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: clothecare_sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: clothe_care_api
            MYSQL_USER: ClotheCare
            MYSQL_PASSWORD: ClotheCare
        restart: always
        ports:
          - 33060:3306

    clothecare_php:
        build: .docker/php
        container_name: clothecare_sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=clothecare_sf4_maildev
        depends_on:
          - maildev
          - clothecare_mysql
        restart: always

    imageReader:
      image: laundrysymbolreader/reader
      container_name: clothecare_sf4_imageReader
      environment:
        - 
      depends_on:
        - clothecare_php
      restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: clothecare_sf4_phpmyadmin
        environment:
          PMA_HOST: clothecare_mysql
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: root
        ports:
            - 8080:80
        links:
            - clothecare_mysql
        restart: always

    maildev:
        image: djfarrelly/maildev
        container_name: clothecare_sf4_maildev
        ports:
          - 8001:80
        restart: always
