<?php

namespace App\Controller;

use App\Entity\Label;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use phpseclib\Net\SSH2;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class LabelController extends AbstractController
{
    /**
     * @Route("/api/image/test", name="test_upload")
     */
    public function TestReaderFunction(Request $request,  ValidatorInterface $validator)
    {
        $ssh = new SSH2('urenapi.nl');
        if (!$ssh->login('root', 'L1ndseyT1m')) {
            exit('Login Failed');
        }
        dd($ssh->exec('./laundry-symbol-reader/bin/laundry-symbol-reader-dk ClotheCareAPI/public/Labels/'.'02.jpeg'));

        return new Response(
        );
    }

    /**
     * @Route("/api/image/upload", name="Photo_upload")
     */
    public function PhotoUpload(Request $request,  ValidatorInterface $validator)
    {

        $data = $request->files->get('data');

        /** @var UploadedFile $uploadedFile */
        $em = $this->getDoctrine()->getManager();
        $Photo = new Label();
        $file = $uploadedFile;
        $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
       try {
            $file->move(
                $this->getParameter('file_directory'),
                $fileName
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }
        $Photo->setImage($fileName);
        $em->persist($Photo);
        $em->flush();
        return new Response(
            json_encode($uploadedFile)
        );
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
